### PR TITLE
R4 Final Review

### PR DESCRIPTION
**Pull request by owlot**
https://www.arrowair.com/docs/contributing/guides/release-checklist

### CODE REVIEW

**Review by amsmith-pro — CHANGES_REQUESTED** [review]
https://github.com/aetheric-oss/svc-storage/blob/56a655cc5643371e4377d35e2e4130e0e845b075/server/src/resources/base/mod.rs#L269

Can this be handled instead of panicking?

**Comment by amsmith-pro** [comment]
Otherwise looks good! Don't think there were any interface changes in R4 so no updates to ICD or SDD are expected

**Comment by owlot** [comment]
> Otherwise looks good! Don't think there were any interface changes in R4 so no updates to ICD or SDD are expected

Well, actually session_id was added to the flight_plan resource, so I've updated the SDD for it too now :smiley:

**Comment by owlot** [comment]
> https://github.com/aetheric-oss/svc-storage/blob/56a655cc5643371e4377d35e2e4130e0e845b075/server/src/resources/base/mod.rs#L269
> 
> Can this be handled instead of panicking?

fixed: https://github.com/aetheric-oss/svc-storage/pull/107/commits/66476fd29a7d4b5c2cbd7ff687cbf9c7f1fdab97

**Pull request merged**
